spring.application.name=CloudPractice
server.port=8080
auth0.audience=https://dev-security-homework.us.auth0.com/api/v2/
auth0.domain=dev-security-homework.us.auth0.com
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://${auth0.domain}/